// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: easylab/v1/easylab.proto

// EasyLab core + gateway API: the revision-native lab, ops and package
// surfaces. Replaces the hand-written /api/v1/routes. This is the contract the
// Flutter client and the ext servers consume.
package easylabv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "forgejo.develop.10.199.64.20.nip.io/easylab/easylab-proto/easylab/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// LabServiceName is the fully-qualified name of the LabService service.
	LabServiceName = "easylab.v1.LabService"
	// OpsServiceName is the fully-qualified name of the OpsService service.
	OpsServiceName = "easylab.v1.OpsService"
	// RegistryServiceName is the fully-qualified name of the RegistryService service.
	RegistryServiceName = "easylab.v1.RegistryService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// LabServiceHealthProcedure is the fully-qualified name of the LabService's Health RPC.
	LabServiceHealthProcedure = "/easylab.v1.LabService/Health"
	// LabServiceStatusProcedure is the fully-qualified name of the LabService's Status RPC.
	LabServiceStatusProcedure = "/easylab.v1.LabService/Status"
	// LabServiceListReposProcedure is the fully-qualified name of the LabService's ListRepos RPC.
	LabServiceListReposProcedure = "/easylab.v1.LabService/ListRepos"
	// LabServiceCreateRepoProcedure is the fully-qualified name of the LabService's CreateRepo RPC.
	LabServiceCreateRepoProcedure = "/easylab.v1.LabService/CreateRepo"
	// LabServiceDeleteRepoProcedure is the fully-qualified name of the LabService's DeleteRepo RPC.
	LabServiceDeleteRepoProcedure = "/easylab.v1.LabService/DeleteRepo"
	// LabServiceEnsureRepoProcedure is the fully-qualified name of the LabService's EnsureRepo RPC.
	LabServiceEnsureRepoProcedure = "/easylab.v1.LabService/EnsureRepo"
	// LabServiceEnsureOrgProcedure is the fully-qualified name of the LabService's EnsureOrg RPC.
	LabServiceEnsureOrgProcedure = "/easylab.v1.LabService/EnsureOrg"
	// LabServiceForkRepoProcedure is the fully-qualified name of the LabService's ForkRepo RPC.
	LabServiceForkRepoProcedure = "/easylab.v1.LabService/ForkRepo"
	// LabServiceCloneRepoProcedure is the fully-qualified name of the LabService's CloneRepo RPC.
	LabServiceCloneRepoProcedure = "/easylab.v1.LabService/CloneRepo"
	// LabServiceTreeProcedure is the fully-qualified name of the LabService's Tree RPC.
	LabServiceTreeProcedure = "/easylab.v1.LabService/Tree"
	// LabServiceReadBlobProcedure is the fully-qualified name of the LabService's ReadBlob RPC.
	LabServiceReadBlobProcedure = "/easylab.v1.LabService/ReadBlob"
	// LabServiceWriteBlobProcedure is the fully-qualified name of the LabService's WriteBlob RPC.
	LabServiceWriteBlobProcedure = "/easylab.v1.LabService/WriteBlob"
	// LabServiceLogProcedure is the fully-qualified name of the LabService's Log RPC.
	LabServiceLogProcedure = "/easylab.v1.LabService/Log"
	// LabServiceTagsProcedure is the fully-qualified name of the LabService's Tags RPC.
	LabServiceTagsProcedure = "/easylab.v1.LabService/Tags"
	// LabServiceBranchesProcedure is the fully-qualified name of the LabService's Branches RPC.
	LabServiceBranchesProcedure = "/easylab.v1.LabService/Branches"
	// LabServiceRevisionsProcedure is the fully-qualified name of the LabService's Revisions RPC.
	LabServiceRevisionsProcedure = "/easylab.v1.LabService/Revisions"
	// LabServiceDiffProcedure is the fully-qualified name of the LabService's Diff RPC.
	LabServiceDiffProcedure = "/easylab.v1.LabService/Diff"
	// LabServiceBlameProcedure is the fully-qualified name of the LabService's Blame RPC.
	LabServiceBlameProcedure = "/easylab.v1.LabService/Blame"
	// LabServiceDeleteBranchProcedure is the fully-qualified name of the LabService's DeleteBranch RPC.
	LabServiceDeleteBranchProcedure = "/easylab.v1.LabService/DeleteBranch"
	// LabServiceCreateBranchProcedure is the fully-qualified name of the LabService's CreateBranch RPC.
	LabServiceCreateBranchProcedure = "/easylab.v1.LabService/CreateBranch"
	// LabServiceFileHistoryProcedure is the fully-qualified name of the LabService's FileHistory RPC.
	LabServiceFileHistoryProcedure = "/easylab.v1.LabService/FileHistory"
	// OpsServiceOpsStatusProcedure is the fully-qualified name of the OpsService's OpsStatus RPC.
	OpsServiceOpsStatusProcedure = "/easylab.v1.OpsService/OpsStatus"
	// OpsServiceListNamespacesProcedure is the fully-qualified name of the OpsService's ListNamespaces
	// RPC.
	OpsServiceListNamespacesProcedure = "/easylab.v1.OpsService/ListNamespaces"
	// OpsServiceListServicesProcedure is the fully-qualified name of the OpsService's ListServices RPC.
	OpsServiceListServicesProcedure = "/easylab.v1.OpsService/ListServices"
	// OpsServiceGetServiceProcedure is the fully-qualified name of the OpsService's GetService RPC.
	OpsServiceGetServiceProcedure = "/easylab.v1.OpsService/GetService"
	// OpsServiceLaunchServiceProcedure is the fully-qualified name of the OpsService's LaunchService
	// RPC.
	OpsServiceLaunchServiceProcedure = "/easylab.v1.OpsService/LaunchService"
	// OpsServiceDeleteServiceProcedure is the fully-qualified name of the OpsService's DeleteService
	// RPC.
	OpsServiceDeleteServiceProcedure = "/easylab.v1.OpsService/DeleteService"
	// OpsServiceScaleServiceProcedure is the fully-qualified name of the OpsService's ScaleService RPC.
	OpsServiceScaleServiceProcedure = "/easylab.v1.OpsService/ScaleService"
	// OpsServiceSandboxExecProcedure is the fully-qualified name of the OpsService's SandboxExec RPC.
	OpsServiceSandboxExecProcedure = "/easylab.v1.OpsService/SandboxExec"
	// OpsServiceSandboxReadProcedure is the fully-qualified name of the OpsService's SandboxRead RPC.
	OpsServiceSandboxReadProcedure = "/easylab.v1.OpsService/SandboxRead"
	// OpsServiceSandboxWriteProcedure is the fully-qualified name of the OpsService's SandboxWrite RPC.
	OpsServiceSandboxWriteProcedure = "/easylab.v1.OpsService/SandboxWrite"
	// OpsServiceSandboxJobKillProcedure is the fully-qualified name of the OpsService's SandboxJobKill
	// RPC.
	OpsServiceSandboxJobKillProcedure = "/easylab.v1.OpsService/SandboxJobKill"
	// OpsServiceListTasksProcedure is the fully-qualified name of the OpsService's ListTasks RPC.
	OpsServiceListTasksProcedure = "/easylab.v1.OpsService/ListTasks"
	// OpsServiceGetTaskProcedure is the fully-qualified name of the OpsService's GetTask RPC.
	OpsServiceGetTaskProcedure = "/easylab.v1.OpsService/GetTask"
	// OpsServiceBuildProcedure is the fully-qualified name of the OpsService's Build RPC.
	OpsServiceBuildProcedure = "/easylab.v1.OpsService/Build"
	// OpsServiceRunProcedure is the fully-qualified name of the OpsService's Run RPC.
	OpsServiceRunProcedure = "/easylab.v1.OpsService/Run"
	// OpsServiceTaskLogProcedure is the fully-qualified name of the OpsService's TaskLog RPC.
	OpsServiceTaskLogProcedure = "/easylab.v1.OpsService/TaskLog"
	// RegistryServiceListPackageTypesProcedure is the fully-qualified name of the RegistryService's
	// ListPackageTypes RPC.
	RegistryServiceListPackageTypesProcedure = "/easylab.v1.RegistryService/ListPackageTypes"
	// RegistryServiceListPackagesProcedure is the fully-qualified name of the RegistryService's
	// ListPackages RPC.
	RegistryServiceListPackagesProcedure = "/easylab.v1.RegistryService/ListPackages"
	// RegistryServicePackageVersionsProcedure is the fully-qualified name of the RegistryService's
	// PackageVersions RPC.
	RegistryServicePackageVersionsProcedure = "/easylab.v1.RegistryService/PackageVersions"
	// RegistryServiceDeletePackageProcedure is the fully-qualified name of the RegistryService's
	// DeletePackage RPC.
	RegistryServiceDeletePackageProcedure = "/easylab.v1.RegistryService/DeletePackage"
	// RegistryServiceDeletePackageVersionProcedure is the fully-qualified name of the RegistryService's
	// DeletePackageVersion RPC.
	RegistryServiceDeletePackageVersionProcedure = "/easylab.v1.RegistryService/DeletePackageVersion"
	// RegistryServiceListPublishSpecsProcedure is the fully-qualified name of the RegistryService's
	// ListPublishSpecs RPC.
	RegistryServiceListPublishSpecsProcedure = "/easylab.v1.RegistryService/ListPublishSpecs"
)

// LabServiceClient is a client for the easylab.v1.LabService service.
type LabServiceClient interface {
	Health(context.Context, *connect.Request[v1.HealthRequest]) (*connect.Response[v1.HealthResponse], error)
	Status(context.Context, *connect.Request[v1.StatusRequest]) (*connect.Response[v1.StatusResponse], error)
	ListRepos(context.Context, *connect.Request[v1.ListReposRequest]) (*connect.Response[v1.ListReposResponse], error)
	CreateRepo(context.Context, *connect.Request[v1.CreateRepoRequest]) (*connect.Response[v1.CreateRepoResponse], error)
	DeleteRepo(context.Context, *connect.Request[v1.DeleteRepoRequest]) (*connect.Response[v1.DeleteRepoResponse], error)
	EnsureRepo(context.Context, *connect.Request[v1.EnsureRepoRequest]) (*connect.Response[v1.EnsureRepoResponse], error)
	EnsureOrg(context.Context, *connect.Request[v1.EnsureOrgRequest]) (*connect.Response[v1.EnsureOrgResponse], error)
	ForkRepo(context.Context, *connect.Request[v1.ForkRepoRequest]) (*connect.Response[v1.ForkRepoResponse], error)
	CloneRepo(context.Context, *connect.Request[v1.CloneRepoRequest]) (*connect.Response[v1.CloneRepoResponse], error)
	Tree(context.Context, *connect.Request[v1.TreeRequest]) (*connect.Response[v1.TreeResponse], error)
	ReadBlob(context.Context, *connect.Request[v1.ReadBlobRequest]) (*connect.Response[v1.ReadBlobResponse], error)
	WriteBlob(context.Context, *connect.Request[v1.WriteBlobRequest]) (*connect.Response[v1.WriteBlobResponse], error)
	Log(context.Context, *connect.Request[v1.LogRequest]) (*connect.Response[v1.LogResponse], error)
	Tags(context.Context, *connect.Request[v1.TagsRequest]) (*connect.Response[v1.TagsResponse], error)
	Branches(context.Context, *connect.Request[v1.BranchesRequest]) (*connect.Response[v1.BranchesResponse], error)
	Revisions(context.Context, *connect.Request[v1.RevisionsRequest]) (*connect.Response[v1.RevisionsResponse], error)
	Diff(context.Context, *connect.Request[v1.DiffRequest]) (*connect.Response[v1.DiffResponse], error)
	Blame(context.Context, *connect.Request[v1.BlameRequest]) (*connect.Response[v1.BlameResponse], error)
	DeleteBranch(context.Context, *connect.Request[v1.DeleteBranchRequest]) (*connect.Response[v1.DeleteBranchResponse], error)
	CreateBranch(context.Context, *connect.Request[v1.CreateBranchRequest]) (*connect.Response[v1.CreateBranchResponse], error)
	FileHistory(context.Context, *connect.Request[v1.FileHistoryRequest]) (*connect.Response[v1.FileHistoryResponse], error)
}

// NewLabServiceClient constructs a client for the easylab.v1.LabService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewLabServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) LabServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	labServiceMethods := v1.File_easylab_v1_easylab_proto.Services().ByName("LabService").Methods()
	return &labServiceClient{
		health: connect.NewClient[v1.HealthRequest, v1.HealthResponse](
			httpClient,
			baseURL+LabServiceHealthProcedure,
			connect.WithSchema(labServiceMethods.ByName("Health")),
			connect.WithClientOptions(opts...),
		),
		status: connect.NewClient[v1.StatusRequest, v1.StatusResponse](
			httpClient,
			baseURL+LabServiceStatusProcedure,
			connect.WithSchema(labServiceMethods.ByName("Status")),
			connect.WithClientOptions(opts...),
		),
		listRepos: connect.NewClient[v1.ListReposRequest, v1.ListReposResponse](
			httpClient,
			baseURL+LabServiceListReposProcedure,
			connect.WithSchema(labServiceMethods.ByName("ListRepos")),
			connect.WithClientOptions(opts...),
		),
		createRepo: connect.NewClient[v1.CreateRepoRequest, v1.CreateRepoResponse](
			httpClient,
			baseURL+LabServiceCreateRepoProcedure,
			connect.WithSchema(labServiceMethods.ByName("CreateRepo")),
			connect.WithClientOptions(opts...),
		),
		deleteRepo: connect.NewClient[v1.DeleteRepoRequest, v1.DeleteRepoResponse](
			httpClient,
			baseURL+LabServiceDeleteRepoProcedure,
			connect.WithSchema(labServiceMethods.ByName("DeleteRepo")),
			connect.WithClientOptions(opts...),
		),
		ensureRepo: connect.NewClient[v1.EnsureRepoRequest, v1.EnsureRepoResponse](
			httpClient,
			baseURL+LabServiceEnsureRepoProcedure,
			connect.WithSchema(labServiceMethods.ByName("EnsureRepo")),
			connect.WithClientOptions(opts...),
		),
		ensureOrg: connect.NewClient[v1.EnsureOrgRequest, v1.EnsureOrgResponse](
			httpClient,
			baseURL+LabServiceEnsureOrgProcedure,
			connect.WithSchema(labServiceMethods.ByName("EnsureOrg")),
			connect.WithClientOptions(opts...),
		),
		forkRepo: connect.NewClient[v1.ForkRepoRequest, v1.ForkRepoResponse](
			httpClient,
			baseURL+LabServiceForkRepoProcedure,
			connect.WithSchema(labServiceMethods.ByName("ForkRepo")),
			connect.WithClientOptions(opts...),
		),
		cloneRepo: connect.NewClient[v1.CloneRepoRequest, v1.CloneRepoResponse](
			httpClient,
			baseURL+LabServiceCloneRepoProcedure,
			connect.WithSchema(labServiceMethods.ByName("CloneRepo")),
			connect.WithClientOptions(opts...),
		),
		tree: connect.NewClient[v1.TreeRequest, v1.TreeResponse](
			httpClient,
			baseURL+LabServiceTreeProcedure,
			connect.WithSchema(labServiceMethods.ByName("Tree")),
			connect.WithClientOptions(opts...),
		),
		readBlob: connect.NewClient[v1.ReadBlobRequest, v1.ReadBlobResponse](
			httpClient,
			baseURL+LabServiceReadBlobProcedure,
			connect.WithSchema(labServiceMethods.ByName("ReadBlob")),
			connect.WithClientOptions(opts...),
		),
		writeBlob: connect.NewClient[v1.WriteBlobRequest, v1.WriteBlobResponse](
			httpClient,
			baseURL+LabServiceWriteBlobProcedure,
			connect.WithSchema(labServiceMethods.ByName("WriteBlob")),
			connect.WithClientOptions(opts...),
		),
		log: connect.NewClient[v1.LogRequest, v1.LogResponse](
			httpClient,
			baseURL+LabServiceLogProcedure,
			connect.WithSchema(labServiceMethods.ByName("Log")),
			connect.WithClientOptions(opts...),
		),
		tags: connect.NewClient[v1.TagsRequest, v1.TagsResponse](
			httpClient,
			baseURL+LabServiceTagsProcedure,
			connect.WithSchema(labServiceMethods.ByName("Tags")),
			connect.WithClientOptions(opts...),
		),
		branches: connect.NewClient[v1.BranchesRequest, v1.BranchesResponse](
			httpClient,
			baseURL+LabServiceBranchesProcedure,
			connect.WithSchema(labServiceMethods.ByName("Branches")),
			connect.WithClientOptions(opts...),
		),
		revisions: connect.NewClient[v1.RevisionsRequest, v1.RevisionsResponse](
			httpClient,
			baseURL+LabServiceRevisionsProcedure,
			connect.WithSchema(labServiceMethods.ByName("Revisions")),
			connect.WithClientOptions(opts...),
		),
		diff: connect.NewClient[v1.DiffRequest, v1.DiffResponse](
			httpClient,
			baseURL+LabServiceDiffProcedure,
			connect.WithSchema(labServiceMethods.ByName("Diff")),
			connect.WithClientOptions(opts...),
		),
		blame: connect.NewClient[v1.BlameRequest, v1.BlameResponse](
			httpClient,
			baseURL+LabServiceBlameProcedure,
			connect.WithSchema(labServiceMethods.ByName("Blame")),
			connect.WithClientOptions(opts...),
		),
		deleteBranch: connect.NewClient[v1.DeleteBranchRequest, v1.DeleteBranchResponse](
			httpClient,
			baseURL+LabServiceDeleteBranchProcedure,
			connect.WithSchema(labServiceMethods.ByName("DeleteBranch")),
			connect.WithClientOptions(opts...),
		),
		createBranch: connect.NewClient[v1.CreateBranchRequest, v1.CreateBranchResponse](
			httpClient,
			baseURL+LabServiceCreateBranchProcedure,
			connect.WithSchema(labServiceMethods.ByName("CreateBranch")),
			connect.WithClientOptions(opts...),
		),
		fileHistory: connect.NewClient[v1.FileHistoryRequest, v1.FileHistoryResponse](
			httpClient,
			baseURL+LabServiceFileHistoryProcedure,
			connect.WithSchema(labServiceMethods.ByName("FileHistory")),
			connect.WithClientOptions(opts...),
		),
	}
}

// labServiceClient implements LabServiceClient.
type labServiceClient struct {
	health       *connect.Client[v1.HealthRequest, v1.HealthResponse]
	status       *connect.Client[v1.StatusRequest, v1.StatusResponse]
	listRepos    *connect.Client[v1.ListReposRequest, v1.ListReposResponse]
	createRepo   *connect.Client[v1.CreateRepoRequest, v1.CreateRepoResponse]
	deleteRepo   *connect.Client[v1.DeleteRepoRequest, v1.DeleteRepoResponse]
	ensureRepo   *connect.Client[v1.EnsureRepoRequest, v1.EnsureRepoResponse]
	ensureOrg    *connect.Client[v1.EnsureOrgRequest, v1.EnsureOrgResponse]
	forkRepo     *connect.Client[v1.ForkRepoRequest, v1.ForkRepoResponse]
	cloneRepo    *connect.Client[v1.CloneRepoRequest, v1.CloneRepoResponse]
	tree         *connect.Client[v1.TreeRequest, v1.TreeResponse]
	readBlob     *connect.Client[v1.ReadBlobRequest, v1.ReadBlobResponse]
	writeBlob    *connect.Client[v1.WriteBlobRequest, v1.WriteBlobResponse]
	log          *connect.Client[v1.LogRequest, v1.LogResponse]
	tags         *connect.Client[v1.TagsRequest, v1.TagsResponse]
	branches     *connect.Client[v1.BranchesRequest, v1.BranchesResponse]
	revisions    *connect.Client[v1.RevisionsRequest, v1.RevisionsResponse]
	diff         *connect.Client[v1.DiffRequest, v1.DiffResponse]
	blame        *connect.Client[v1.BlameRequest, v1.BlameResponse]
	deleteBranch *connect.Client[v1.DeleteBranchRequest, v1.DeleteBranchResponse]
	createBranch *connect.Client[v1.CreateBranchRequest, v1.CreateBranchResponse]
	fileHistory  *connect.Client[v1.FileHistoryRequest, v1.FileHistoryResponse]
}

// Health calls easylab.v1.LabService.Health.
func (c *labServiceClient) Health(ctx context.Context, req *connect.Request[v1.HealthRequest]) (*connect.Response[v1.HealthResponse], error) {
	return c.health.CallUnary(ctx, req)
}

// Status calls easylab.v1.LabService.Status.
func (c *labServiceClient) Status(ctx context.Context, req *connect.Request[v1.StatusRequest]) (*connect.Response[v1.StatusResponse], error) {
	return c.status.CallUnary(ctx, req)
}

// ListRepos calls easylab.v1.LabService.ListRepos.
func (c *labServiceClient) ListRepos(ctx context.Context, req *connect.Request[v1.ListReposRequest]) (*connect.Response[v1.ListReposResponse], error) {
	return c.listRepos.CallUnary(ctx, req)
}

// CreateRepo calls easylab.v1.LabService.CreateRepo.
func (c *labServiceClient) CreateRepo(ctx context.Context, req *connect.Request[v1.CreateRepoRequest]) (*connect.Response[v1.CreateRepoResponse], error) {
	return c.createRepo.CallUnary(ctx, req)
}

// DeleteRepo calls easylab.v1.LabService.DeleteRepo.
func (c *labServiceClient) DeleteRepo(ctx context.Context, req *connect.Request[v1.DeleteRepoRequest]) (*connect.Response[v1.DeleteRepoResponse], error) {
	return c.deleteRepo.CallUnary(ctx, req)
}

// EnsureRepo calls easylab.v1.LabService.EnsureRepo.
func (c *labServiceClient) EnsureRepo(ctx context.Context, req *connect.Request[v1.EnsureRepoRequest]) (*connect.Response[v1.EnsureRepoResponse], error) {
	return c.ensureRepo.CallUnary(ctx, req)
}

// EnsureOrg calls easylab.v1.LabService.EnsureOrg.
func (c *labServiceClient) EnsureOrg(ctx context.Context, req *connect.Request[v1.EnsureOrgRequest]) (*connect.Response[v1.EnsureOrgResponse], error) {
	return c.ensureOrg.CallUnary(ctx, req)
}

// ForkRepo calls easylab.v1.LabService.ForkRepo.
func (c *labServiceClient) ForkRepo(ctx context.Context, req *connect.Request[v1.ForkRepoRequest]) (*connect.Response[v1.ForkRepoResponse], error) {
	return c.forkRepo.CallUnary(ctx, req)
}

// CloneRepo calls easylab.v1.LabService.CloneRepo.
func (c *labServiceClient) CloneRepo(ctx context.Context, req *connect.Request[v1.CloneRepoRequest]) (*connect.Response[v1.CloneRepoResponse], error) {
	return c.cloneRepo.CallUnary(ctx, req)
}

// Tree calls easylab.v1.LabService.Tree.
func (c *labServiceClient) Tree(ctx context.Context, req *connect.Request[v1.TreeRequest]) (*connect.Response[v1.TreeResponse], error) {
	return c.tree.CallUnary(ctx, req)
}

// ReadBlob calls easylab.v1.LabService.ReadBlob.
func (c *labServiceClient) ReadBlob(ctx context.Context, req *connect.Request[v1.ReadBlobRequest]) (*connect.Response[v1.ReadBlobResponse], error) {
	return c.readBlob.CallUnary(ctx, req)
}

// WriteBlob calls easylab.v1.LabService.WriteBlob.
func (c *labServiceClient) WriteBlob(ctx context.Context, req *connect.Request[v1.WriteBlobRequest]) (*connect.Response[v1.WriteBlobResponse], error) {
	return c.writeBlob.CallUnary(ctx, req)
}

// Log calls easylab.v1.LabService.Log.
func (c *labServiceClient) Log(ctx context.Context, req *connect.Request[v1.LogRequest]) (*connect.Response[v1.LogResponse], error) {
	return c.log.CallUnary(ctx, req)
}

// Tags calls easylab.v1.LabService.Tags.
func (c *labServiceClient) Tags(ctx context.Context, req *connect.Request[v1.TagsRequest]) (*connect.Response[v1.TagsResponse], error) {
	return c.tags.CallUnary(ctx, req)
}

// Branches calls easylab.v1.LabService.Branches.
func (c *labServiceClient) Branches(ctx context.Context, req *connect.Request[v1.BranchesRequest]) (*connect.Response[v1.BranchesResponse], error) {
	return c.branches.CallUnary(ctx, req)
}

// Revisions calls easylab.v1.LabService.Revisions.
func (c *labServiceClient) Revisions(ctx context.Context, req *connect.Request[v1.RevisionsRequest]) (*connect.Response[v1.RevisionsResponse], error) {
	return c.revisions.CallUnary(ctx, req)
}

// Diff calls easylab.v1.LabService.Diff.
func (c *labServiceClient) Diff(ctx context.Context, req *connect.Request[v1.DiffRequest]) (*connect.Response[v1.DiffResponse], error) {
	return c.diff.CallUnary(ctx, req)
}

// Blame calls easylab.v1.LabService.Blame.
func (c *labServiceClient) Blame(ctx context.Context, req *connect.Request[v1.BlameRequest]) (*connect.Response[v1.BlameResponse], error) {
	return c.blame.CallUnary(ctx, req)
}

// DeleteBranch calls easylab.v1.LabService.DeleteBranch.
func (c *labServiceClient) DeleteBranch(ctx context.Context, req *connect.Request[v1.DeleteBranchRequest]) (*connect.Response[v1.DeleteBranchResponse], error) {
	return c.deleteBranch.CallUnary(ctx, req)
}

// CreateBranch calls easylab.v1.LabService.CreateBranch.
func (c *labServiceClient) CreateBranch(ctx context.Context, req *connect.Request[v1.CreateBranchRequest]) (*connect.Response[v1.CreateBranchResponse], error) {
	return c.createBranch.CallUnary(ctx, req)
}

// FileHistory calls easylab.v1.LabService.FileHistory.
func (c *labServiceClient) FileHistory(ctx context.Context, req *connect.Request[v1.FileHistoryRequest]) (*connect.Response[v1.FileHistoryResponse], error) {
	return c.fileHistory.CallUnary(ctx, req)
}

// LabServiceHandler is an implementation of the easylab.v1.LabService service.
type LabServiceHandler interface {
	Health(context.Context, *connect.Request[v1.HealthRequest]) (*connect.Response[v1.HealthResponse], error)
	Status(context.Context, *connect.Request[v1.StatusRequest]) (*connect.Response[v1.StatusResponse], error)
	ListRepos(context.Context, *connect.Request[v1.ListReposRequest]) (*connect.Response[v1.ListReposResponse], error)
	CreateRepo(context.Context, *connect.Request[v1.CreateRepoRequest]) (*connect.Response[v1.CreateRepoResponse], error)
	DeleteRepo(context.Context, *connect.Request[v1.DeleteRepoRequest]) (*connect.Response[v1.DeleteRepoResponse], error)
	EnsureRepo(context.Context, *connect.Request[v1.EnsureRepoRequest]) (*connect.Response[v1.EnsureRepoResponse], error)
	EnsureOrg(context.Context, *connect.Request[v1.EnsureOrgRequest]) (*connect.Response[v1.EnsureOrgResponse], error)
	ForkRepo(context.Context, *connect.Request[v1.ForkRepoRequest]) (*connect.Response[v1.ForkRepoResponse], error)
	CloneRepo(context.Context, *connect.Request[v1.CloneRepoRequest]) (*connect.Response[v1.CloneRepoResponse], error)
	Tree(context.Context, *connect.Request[v1.TreeRequest]) (*connect.Response[v1.TreeResponse], error)
	ReadBlob(context.Context, *connect.Request[v1.ReadBlobRequest]) (*connect.Response[v1.ReadBlobResponse], error)
	WriteBlob(context.Context, *connect.Request[v1.WriteBlobRequest]) (*connect.Response[v1.WriteBlobResponse], error)
	Log(context.Context, *connect.Request[v1.LogRequest]) (*connect.Response[v1.LogResponse], error)
	Tags(context.Context, *connect.Request[v1.TagsRequest]) (*connect.Response[v1.TagsResponse], error)
	Branches(context.Context, *connect.Request[v1.BranchesRequest]) (*connect.Response[v1.BranchesResponse], error)
	Revisions(context.Context, *connect.Request[v1.RevisionsRequest]) (*connect.Response[v1.RevisionsResponse], error)
	Diff(context.Context, *connect.Request[v1.DiffRequest]) (*connect.Response[v1.DiffResponse], error)
	Blame(context.Context, *connect.Request[v1.BlameRequest]) (*connect.Response[v1.BlameResponse], error)
	DeleteBranch(context.Context, *connect.Request[v1.DeleteBranchRequest]) (*connect.Response[v1.DeleteBranchResponse], error)
	CreateBranch(context.Context, *connect.Request[v1.CreateBranchRequest]) (*connect.Response[v1.CreateBranchResponse], error)
	FileHistory(context.Context, *connect.Request[v1.FileHistoryRequest]) (*connect.Response[v1.FileHistoryResponse], error)
}

// NewLabServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewLabServiceHandler(svc LabServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	labServiceMethods := v1.File_easylab_v1_easylab_proto.Services().ByName("LabService").Methods()
	labServiceHealthHandler := connect.NewUnaryHandler(
		LabServiceHealthProcedure,
		svc.Health,
		connect.WithSchema(labServiceMethods.ByName("Health")),
		connect.WithHandlerOptions(opts...),
	)
	labServiceStatusHandler := connect.NewUnaryHandler(
		LabServiceStatusProcedure,
		svc.Status,
		connect.WithSchema(labServiceMethods.ByName("Status")),
		connect.WithHandlerOptions(opts...),
	)
	labServiceListReposHandler := connect.NewUnaryHandler(
		LabServiceListReposProcedure,
		svc.ListRepos,
		connect.WithSchema(labServiceMethods.ByName("ListRepos")),
		connect.WithHandlerOptions(opts...),
	)
	labServiceCreateRepoHandler := connect.NewUnaryHandler(
		LabServiceCreateRepoProcedure,
		svc.CreateRepo,
		connect.WithSchema(labServiceMethods.ByName("CreateRepo")),
		connect.WithHandlerOptions(opts...),
	)
	labServiceDeleteRepoHandler := connect.NewUnaryHandler(
		LabServiceDeleteRepoProcedure,
		svc.DeleteRepo,
		connect.WithSchema(labServiceMethods.ByName("DeleteRepo")),
		connect.WithHandlerOptions(opts...),
	)
	labServiceEnsureRepoHandler := connect.NewUnaryHandler(
		LabServiceEnsureRepoProcedure,
		svc.EnsureRepo,
		connect.WithSchema(labServiceMethods.ByName("EnsureRepo")),
		connect.WithHandlerOptions(opts...),
	)
	labServiceEnsureOrgHandler := connect.NewUnaryHandler(
		LabServiceEnsureOrgProcedure,
		svc.EnsureOrg,
		connect.WithSchema(labServiceMethods.ByName("EnsureOrg")),
		connect.WithHandlerOptions(opts...),
	)
	labServiceForkRepoHandler := connect.NewUnaryHandler(
		LabServiceForkRepoProcedure,
		svc.ForkRepo,
		connect.WithSchema(labServiceMethods.ByName("ForkRepo")),
		connect.WithHandlerOptions(opts...),
	)
	labServiceCloneRepoHandler := connect.NewUnaryHandler(
		LabServiceCloneRepoProcedure,
		svc.CloneRepo,
		connect.WithSchema(labServiceMethods.ByName("CloneRepo")),
		connect.WithHandlerOptions(opts...),
	)
	labServiceTreeHandler := connect.NewUnaryHandler(
		LabServiceTreeProcedure,
		svc.Tree,
		connect.WithSchema(labServiceMethods.ByName("Tree")),
		connect.WithHandlerOptions(opts...),
	)
	labServiceReadBlobHandler := connect.NewUnaryHandler(
		LabServiceReadBlobProcedure,
		svc.ReadBlob,
		connect.WithSchema(labServiceMethods.ByName("ReadBlob")),
		connect.WithHandlerOptions(opts...),
	)
	labServiceWriteBlobHandler := connect.NewUnaryHandler(
		LabServiceWriteBlobProcedure,
		svc.WriteBlob,
		connect.WithSchema(labServiceMethods.ByName("WriteBlob")),
		connect.WithHandlerOptions(opts...),
	)
	labServiceLogHandler := connect.NewUnaryHandler(
		LabServiceLogProcedure,
		svc.Log,
		connect.WithSchema(labServiceMethods.ByName("Log")),
		connect.WithHandlerOptions(opts...),
	)
	labServiceTagsHandler := connect.NewUnaryHandler(
		LabServiceTagsProcedure,
		svc.Tags,
		connect.WithSchema(labServiceMethods.ByName("Tags")),
		connect.WithHandlerOptions(opts...),
	)
	labServiceBranchesHandler := connect.NewUnaryHandler(
		LabServiceBranchesProcedure,
		svc.Branches,
		connect.WithSchema(labServiceMethods.ByName("Branches")),
		connect.WithHandlerOptions(opts...),
	)
	labServiceRevisionsHandler := connect.NewUnaryHandler(
		LabServiceRevisionsProcedure,
		svc.Revisions,
		connect.WithSchema(labServiceMethods.ByName("Revisions")),
		connect.WithHandlerOptions(opts...),
	)
	labServiceDiffHandler := connect.NewUnaryHandler(
		LabServiceDiffProcedure,
		svc.Diff,
		connect.WithSchema(labServiceMethods.ByName("Diff")),
		connect.WithHandlerOptions(opts...),
	)
	labServiceBlameHandler := connect.NewUnaryHandler(
		LabServiceBlameProcedure,
		svc.Blame,
		connect.WithSchema(labServiceMethods.ByName("Blame")),
		connect.WithHandlerOptions(opts...),
	)
	labServiceDeleteBranchHandler := connect.NewUnaryHandler(
		LabServiceDeleteBranchProcedure,
		svc.DeleteBranch,
		connect.WithSchema(labServiceMethods.ByName("DeleteBranch")),
		connect.WithHandlerOptions(opts...),
	)
	labServiceCreateBranchHandler := connect.NewUnaryHandler(
		LabServiceCreateBranchProcedure,
		svc.CreateBranch,
		connect.WithSchema(labServiceMethods.ByName("CreateBranch")),
		connect.WithHandlerOptions(opts...),
	)
	labServiceFileHistoryHandler := connect.NewUnaryHandler(
		LabServiceFileHistoryProcedure,
		svc.FileHistory,
		connect.WithSchema(labServiceMethods.ByName("FileHistory")),
		connect.WithHandlerOptions(opts...),
	)
	return "/easylab.v1.LabService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case LabServiceHealthProcedure:
			labServiceHealthHandler.ServeHTTP(w, r)
		case LabServiceStatusProcedure:
			labServiceStatusHandler.ServeHTTP(w, r)
		case LabServiceListReposProcedure:
			labServiceListReposHandler.ServeHTTP(w, r)
		case LabServiceCreateRepoProcedure:
			labServiceCreateRepoHandler.ServeHTTP(w, r)
		case LabServiceDeleteRepoProcedure:
			labServiceDeleteRepoHandler.ServeHTTP(w, r)
		case LabServiceEnsureRepoProcedure:
			labServiceEnsureRepoHandler.ServeHTTP(w, r)
		case LabServiceEnsureOrgProcedure:
			labServiceEnsureOrgHandler.ServeHTTP(w, r)
		case LabServiceForkRepoProcedure:
			labServiceForkRepoHandler.ServeHTTP(w, r)
		case LabServiceCloneRepoProcedure:
			labServiceCloneRepoHandler.ServeHTTP(w, r)
		case LabServiceTreeProcedure:
			labServiceTreeHandler.ServeHTTP(w, r)
		case LabServiceReadBlobProcedure:
			labServiceReadBlobHandler.ServeHTTP(w, r)
		case LabServiceWriteBlobProcedure:
			labServiceWriteBlobHandler.ServeHTTP(w, r)
		case LabServiceLogProcedure:
			labServiceLogHandler.ServeHTTP(w, r)
		case LabServiceTagsProcedure:
			labServiceTagsHandler.ServeHTTP(w, r)
		case LabServiceBranchesProcedure:
			labServiceBranchesHandler.ServeHTTP(w, r)
		case LabServiceRevisionsProcedure:
			labServiceRevisionsHandler.ServeHTTP(w, r)
		case LabServiceDiffProcedure:
			labServiceDiffHandler.ServeHTTP(w, r)
		case LabServiceBlameProcedure:
			labServiceBlameHandler.ServeHTTP(w, r)
		case LabServiceDeleteBranchProcedure:
			labServiceDeleteBranchHandler.ServeHTTP(w, r)
		case LabServiceCreateBranchProcedure:
			labServiceCreateBranchHandler.ServeHTTP(w, r)
		case LabServiceFileHistoryProcedure:
			labServiceFileHistoryHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedLabServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedLabServiceHandler struct{}

func (UnimplementedLabServiceHandler) Health(context.Context, *connect.Request[v1.HealthRequest]) (*connect.Response[v1.HealthResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("easylab.v1.LabService.Health is not implemented"))
}

func (UnimplementedLabServiceHandler) Status(context.Context, *connect.Request[v1.StatusRequest]) (*connect.Response[v1.StatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("easylab.v1.LabService.Status is not implemented"))
}

func (UnimplementedLabServiceHandler) ListRepos(context.Context, *connect.Request[v1.ListReposRequest]) (*connect.Response[v1.ListReposResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("easylab.v1.LabService.ListRepos is not implemented"))
}

func (UnimplementedLabServiceHandler) CreateRepo(context.Context, *connect.Request[v1.CreateRepoRequest]) (*connect.Response[v1.CreateRepoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("easylab.v1.LabService.CreateRepo is not implemented"))
}

func (UnimplementedLabServiceHandler) DeleteRepo(context.Context, *connect.Request[v1.DeleteRepoRequest]) (*connect.Response[v1.DeleteRepoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("easylab.v1.LabService.DeleteRepo is not implemented"))
}

func (UnimplementedLabServiceHandler) EnsureRepo(context.Context, *connect.Request[v1.EnsureRepoRequest]) (*connect.Response[v1.EnsureRepoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("easylab.v1.LabService.EnsureRepo is not implemented"))
}

func (UnimplementedLabServiceHandler) EnsureOrg(context.Context, *connect.Request[v1.EnsureOrgRequest]) (*connect.Response[v1.EnsureOrgResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("easylab.v1.LabService.EnsureOrg is not implemented"))
}

func (UnimplementedLabServiceHandler) ForkRepo(context.Context, *connect.Request[v1.ForkRepoRequest]) (*connect.Response[v1.ForkRepoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("easylab.v1.LabService.ForkRepo is not implemented"))
}

func (UnimplementedLabServiceHandler) CloneRepo(context.Context, *connect.Request[v1.CloneRepoRequest]) (*connect.Response[v1.CloneRepoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("easylab.v1.LabService.CloneRepo is not implemented"))
}

func (UnimplementedLabServiceHandler) Tree(context.Context, *connect.Request[v1.TreeRequest]) (*connect.Response[v1.TreeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("easylab.v1.LabService.Tree is not implemented"))
}

func (UnimplementedLabServiceHandler) ReadBlob(context.Context, *connect.Request[v1.ReadBlobRequest]) (*connect.Response[v1.ReadBlobResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("easylab.v1.LabService.ReadBlob is not implemented"))
}

func (UnimplementedLabServiceHandler) WriteBlob(context.Context, *connect.Request[v1.WriteBlobRequest]) (*connect.Response[v1.WriteBlobResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("easylab.v1.LabService.WriteBlob is not implemented"))
}

func (UnimplementedLabServiceHandler) Log(context.Context, *connect.Request[v1.LogRequest]) (*connect.Response[v1.LogResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("easylab.v1.LabService.Log is not implemented"))
}

func (UnimplementedLabServiceHandler) Tags(context.Context, *connect.Request[v1.TagsRequest]) (*connect.Response[v1.TagsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("easylab.v1.LabService.Tags is not implemented"))
}

func (UnimplementedLabServiceHandler) Branches(context.Context, *connect.Request[v1.BranchesRequest]) (*connect.Response[v1.BranchesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("easylab.v1.LabService.Branches is not implemented"))
}

func (UnimplementedLabServiceHandler) Revisions(context.Context, *connect.Request[v1.RevisionsRequest]) (*connect.Response[v1.RevisionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("easylab.v1.LabService.Revisions is not implemented"))
}

func (UnimplementedLabServiceHandler) Diff(context.Context, *connect.Request[v1.DiffRequest]) (*connect.Response[v1.DiffResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("easylab.v1.LabService.Diff is not implemented"))
}

func (UnimplementedLabServiceHandler) Blame(context.Context, *connect.Request[v1.BlameRequest]) (*connect.Response[v1.BlameResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("easylab.v1.LabService.Blame is not implemented"))
}

func (UnimplementedLabServiceHandler) DeleteBranch(context.Context, *connect.Request[v1.DeleteBranchRequest]) (*connect.Response[v1.DeleteBranchResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("easylab.v1.LabService.DeleteBranch is not implemented"))
}

func (UnimplementedLabServiceHandler) CreateBranch(context.Context, *connect.Request[v1.CreateBranchRequest]) (*connect.Response[v1.CreateBranchResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("easylab.v1.LabService.CreateBranch is not implemented"))
}

func (UnimplementedLabServiceHandler) FileHistory(context.Context, *connect.Request[v1.FileHistoryRequest]) (*connect.Response[v1.FileHistoryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("easylab.v1.LabService.FileHistory is not implemented"))
}

// OpsServiceClient is a client for the easylab.v1.OpsService service.
type OpsServiceClient interface {
	OpsStatus(context.Context, *connect.Request[v1.OpsStatusRequest]) (*connect.Response[v1.OpsStatusResponse], error)
	ListNamespaces(context.Context, *connect.Request[v1.ListNamespacesRequest]) (*connect.Response[v1.ListNamespacesResponse], error)
	ListServices(context.Context, *connect.Request[v1.ListServicesRequest]) (*connect.Response[v1.ListServicesResponse], error)
	GetService(context.Context, *connect.Request[v1.GetServiceRequest]) (*connect.Response[v1.GetServiceResponse], error)
	LaunchService(context.Context, *connect.Request[v1.LaunchServiceRequest]) (*connect.Response[v1.LaunchServiceResponse], error)
	DeleteService(context.Context, *connect.Request[v1.DeleteServiceRequest]) (*connect.Response[v1.DeleteServiceResponse], error)
	ScaleService(context.Context, *connect.Request[v1.ScaleServiceRequest]) (*connect.Response[v1.ScaleServiceResponse], error)
	SandboxExec(context.Context, *connect.Request[v1.SandboxExecRequest]) (*connect.Response[v1.SandboxExecResponse], error)
	SandboxRead(context.Context, *connect.Request[v1.SandboxReadRequest]) (*connect.Response[v1.SandboxReadResponse], error)
	SandboxWrite(context.Context, *connect.Request[v1.SandboxWriteRequest]) (*connect.Response[v1.SandboxWriteResponse], error)
	SandboxJobKill(context.Context, *connect.Request[v1.SandboxJobKillRequest]) (*connect.Response[v1.SandboxJobKillResponse], error)
	ListTasks(context.Context, *connect.Request[v1.ListTasksRequest]) (*connect.Response[v1.ListTasksResponse], error)
	GetTask(context.Context, *connect.Request[v1.GetTaskRequest]) (*connect.Response[v1.GetTaskResponse], error)
	Build(context.Context, *connect.Request[v1.BuildRequest]) (*connect.Response[v1.BuildResponse], error)
	Run(context.Context, *connect.Request[v1.RunRequest]) (*connect.Response[v1.RunResponse], error)
	TaskLog(context.Context, *connect.Request[v1.TaskLogRequest]) (*connect.ServerStreamForClient[v1.TaskLogResponse], error)
}

// NewOpsServiceClient constructs a client for the easylab.v1.OpsService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewOpsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) OpsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	opsServiceMethods := v1.File_easylab_v1_easylab_proto.Services().ByName("OpsService").Methods()
	return &opsServiceClient{
		opsStatus: connect.NewClient[v1.OpsStatusRequest, v1.OpsStatusResponse](
			httpClient,
			baseURL+OpsServiceOpsStatusProcedure,
			connect.WithSchema(opsServiceMethods.ByName("OpsStatus")),
			connect.WithClientOptions(opts...),
		),
		listNamespaces: connect.NewClient[v1.ListNamespacesRequest, v1.ListNamespacesResponse](
			httpClient,
			baseURL+OpsServiceListNamespacesProcedure,
			connect.WithSchema(opsServiceMethods.ByName("ListNamespaces")),
			connect.WithClientOptions(opts...),
		),
		listServices: connect.NewClient[v1.ListServicesRequest, v1.ListServicesResponse](
			httpClient,
			baseURL+OpsServiceListServicesProcedure,
			connect.WithSchema(opsServiceMethods.ByName("ListServices")),
			connect.WithClientOptions(opts...),
		),
		getService: connect.NewClient[v1.GetServiceRequest, v1.GetServiceResponse](
			httpClient,
			baseURL+OpsServiceGetServiceProcedure,
			connect.WithSchema(opsServiceMethods.ByName("GetService")),
			connect.WithClientOptions(opts...),
		),
		launchService: connect.NewClient[v1.LaunchServiceRequest, v1.LaunchServiceResponse](
			httpClient,
			baseURL+OpsServiceLaunchServiceProcedure,
			connect.WithSchema(opsServiceMethods.ByName("LaunchService")),
			connect.WithClientOptions(opts...),
		),
		deleteService: connect.NewClient[v1.DeleteServiceRequest, v1.DeleteServiceResponse](
			httpClient,
			baseURL+OpsServiceDeleteServiceProcedure,
			connect.WithSchema(opsServiceMethods.ByName("DeleteService")),
			connect.WithClientOptions(opts...),
		),
		scaleService: connect.NewClient[v1.ScaleServiceRequest, v1.ScaleServiceResponse](
			httpClient,
			baseURL+OpsServiceScaleServiceProcedure,
			connect.WithSchema(opsServiceMethods.ByName("ScaleService")),
			connect.WithClientOptions(opts...),
		),
		sandboxExec: connect.NewClient[v1.SandboxExecRequest, v1.SandboxExecResponse](
			httpClient,
			baseURL+OpsServiceSandboxExecProcedure,
			connect.WithSchema(opsServiceMethods.ByName("SandboxExec")),
			connect.WithClientOptions(opts...),
		),
		sandboxRead: connect.NewClient[v1.SandboxReadRequest, v1.SandboxReadResponse](
			httpClient,
			baseURL+OpsServiceSandboxReadProcedure,
			connect.WithSchema(opsServiceMethods.ByName("SandboxRead")),
			connect.WithClientOptions(opts...),
		),
		sandboxWrite: connect.NewClient[v1.SandboxWriteRequest, v1.SandboxWriteResponse](
			httpClient,
			baseURL+OpsServiceSandboxWriteProcedure,
			connect.WithSchema(opsServiceMethods.ByName("SandboxWrite")),
			connect.WithClientOptions(opts...),
		),
		sandboxJobKill: connect.NewClient[v1.SandboxJobKillRequest, v1.SandboxJobKillResponse](
			httpClient,
			baseURL+OpsServiceSandboxJobKillProcedure,
			connect.WithSchema(opsServiceMethods.ByName("SandboxJobKill")),
			connect.WithClientOptions(opts...),
		),
		listTasks: connect.NewClient[v1.ListTasksRequest, v1.ListTasksResponse](
			httpClient,
			baseURL+OpsServiceListTasksProcedure,
			connect.WithSchema(opsServiceMethods.ByName("ListTasks")),
			connect.WithClientOptions(opts...),
		),
		getTask: connect.NewClient[v1.GetTaskRequest, v1.GetTaskResponse](
			httpClient,
			baseURL+OpsServiceGetTaskProcedure,
			connect.WithSchema(opsServiceMethods.ByName("GetTask")),
			connect.WithClientOptions(opts...),
		),
		build: connect.NewClient[v1.BuildRequest, v1.BuildResponse](
			httpClient,
			baseURL+OpsServiceBuildProcedure,
			connect.WithSchema(opsServiceMethods.ByName("Build")),
			connect.WithClientOptions(opts...),
		),
		run: connect.NewClient[v1.RunRequest, v1.RunResponse](
			httpClient,
			baseURL+OpsServiceRunProcedure,
			connect.WithSchema(opsServiceMethods.ByName("Run")),
			connect.WithClientOptions(opts...),
		),
		taskLog: connect.NewClient[v1.TaskLogRequest, v1.TaskLogResponse](
			httpClient,
			baseURL+OpsServiceTaskLogProcedure,
			connect.WithSchema(opsServiceMethods.ByName("TaskLog")),
			connect.WithClientOptions(opts...),
		),
	}
}

// opsServiceClient implements OpsServiceClient.
type opsServiceClient struct {
	opsStatus      *connect.Client[v1.OpsStatusRequest, v1.OpsStatusResponse]
	listNamespaces *connect.Client[v1.ListNamespacesRequest, v1.ListNamespacesResponse]
	listServices   *connect.Client[v1.ListServicesRequest, v1.ListServicesResponse]
	getService     *connect.Client[v1.GetServiceRequest, v1.GetServiceResponse]
	launchService  *connect.Client[v1.LaunchServiceRequest, v1.LaunchServiceResponse]
	deleteService  *connect.Client[v1.DeleteServiceRequest, v1.DeleteServiceResponse]
	scaleService   *connect.Client[v1.ScaleServiceRequest, v1.ScaleServiceResponse]
	sandboxExec    *connect.Client[v1.SandboxExecRequest, v1.SandboxExecResponse]
	sandboxRead    *connect.Client[v1.SandboxReadRequest, v1.SandboxReadResponse]
	sandboxWrite   *connect.Client[v1.SandboxWriteRequest, v1.SandboxWriteResponse]
	sandboxJobKill *connect.Client[v1.SandboxJobKillRequest, v1.SandboxJobKillResponse]
	listTasks      *connect.Client[v1.ListTasksRequest, v1.ListTasksResponse]
	getTask        *connect.Client[v1.GetTaskRequest, v1.GetTaskResponse]
	build          *connect.Client[v1.BuildRequest, v1.BuildResponse]
	run            *connect.Client[v1.RunRequest, v1.RunResponse]
	taskLog        *connect.Client[v1.TaskLogRequest, v1.TaskLogResponse]
}

// OpsStatus calls easylab.v1.OpsService.OpsStatus.
func (c *opsServiceClient) OpsStatus(ctx context.Context, req *connect.Request[v1.OpsStatusRequest]) (*connect.Response[v1.OpsStatusResponse], error) {
	return c.opsStatus.CallUnary(ctx, req)
}

// ListNamespaces calls easylab.v1.OpsService.ListNamespaces.
func (c *opsServiceClient) ListNamespaces(ctx context.Context, req *connect.Request[v1.ListNamespacesRequest]) (*connect.Response[v1.ListNamespacesResponse], error) {
	return c.listNamespaces.CallUnary(ctx, req)
}

// ListServices calls easylab.v1.OpsService.ListServices.
func (c *opsServiceClient) ListServices(ctx context.Context, req *connect.Request[v1.ListServicesRequest]) (*connect.Response[v1.ListServicesResponse], error) {
	return c.listServices.CallUnary(ctx, req)
}

// GetService calls easylab.v1.OpsService.GetService.
func (c *opsServiceClient) GetService(ctx context.Context, req *connect.Request[v1.GetServiceRequest]) (*connect.Response[v1.GetServiceResponse], error) {
	return c.getService.CallUnary(ctx, req)
}

// LaunchService calls easylab.v1.OpsService.LaunchService.
func (c *opsServiceClient) LaunchService(ctx context.Context, req *connect.Request[v1.LaunchServiceRequest]) (*connect.Response[v1.LaunchServiceResponse], error) {
	return c.launchService.CallUnary(ctx, req)
}

// DeleteService calls easylab.v1.OpsService.DeleteService.
func (c *opsServiceClient) DeleteService(ctx context.Context, req *connect.Request[v1.DeleteServiceRequest]) (*connect.Response[v1.DeleteServiceResponse], error) {
	return c.deleteService.CallUnary(ctx, req)
}

// ScaleService calls easylab.v1.OpsService.ScaleService.
func (c *opsServiceClient) ScaleService(ctx context.Context, req *connect.Request[v1.ScaleServiceRequest]) (*connect.Response[v1.ScaleServiceResponse], error) {
	return c.scaleService.CallUnary(ctx, req)
}

// SandboxExec calls easylab.v1.OpsService.SandboxExec.
func (c *opsServiceClient) SandboxExec(ctx context.Context, req *connect.Request[v1.SandboxExecRequest]) (*connect.Response[v1.SandboxExecResponse], error) {
	return c.sandboxExec.CallUnary(ctx, req)
}

// SandboxRead calls easylab.v1.OpsService.SandboxRead.
func (c *opsServiceClient) SandboxRead(ctx context.Context, req *connect.Request[v1.SandboxReadRequest]) (*connect.Response[v1.SandboxReadResponse], error) {
	return c.sandboxRead.CallUnary(ctx, req)
}

// SandboxWrite calls easylab.v1.OpsService.SandboxWrite.
func (c *opsServiceClient) SandboxWrite(ctx context.Context, req *connect.Request[v1.SandboxWriteRequest]) (*connect.Response[v1.SandboxWriteResponse], error) {
	return c.sandboxWrite.CallUnary(ctx, req)
}

// SandboxJobKill calls easylab.v1.OpsService.SandboxJobKill.
func (c *opsServiceClient) SandboxJobKill(ctx context.Context, req *connect.Request[v1.SandboxJobKillRequest]) (*connect.Response[v1.SandboxJobKillResponse], error) {
	return c.sandboxJobKill.CallUnary(ctx, req)
}

// ListTasks calls easylab.v1.OpsService.ListTasks.
func (c *opsServiceClient) ListTasks(ctx context.Context, req *connect.Request[v1.ListTasksRequest]) (*connect.Response[v1.ListTasksResponse], error) {
	return c.listTasks.CallUnary(ctx, req)
}

// GetTask calls easylab.v1.OpsService.GetTask.
func (c *opsServiceClient) GetTask(ctx context.Context, req *connect.Request[v1.GetTaskRequest]) (*connect.Response[v1.GetTaskResponse], error) {
	return c.getTask.CallUnary(ctx, req)
}

// Build calls easylab.v1.OpsService.Build.
func (c *opsServiceClient) Build(ctx context.Context, req *connect.Request[v1.BuildRequest]) (*connect.Response[v1.BuildResponse], error) {
	return c.build.CallUnary(ctx, req)
}

// Run calls easylab.v1.OpsService.Run.
func (c *opsServiceClient) Run(ctx context.Context, req *connect.Request[v1.RunRequest]) (*connect.Response[v1.RunResponse], error) {
	return c.run.CallUnary(ctx, req)
}

// TaskLog calls easylab.v1.OpsService.TaskLog.
func (c *opsServiceClient) TaskLog(ctx context.Context, req *connect.Request[v1.TaskLogRequest]) (*connect.ServerStreamForClient[v1.TaskLogResponse], error) {
	return c.taskLog.CallServerStream(ctx, req)
}

// OpsServiceHandler is an implementation of the easylab.v1.OpsService service.
type OpsServiceHandler interface {
	OpsStatus(context.Context, *connect.Request[v1.OpsStatusRequest]) (*connect.Response[v1.OpsStatusResponse], error)
	ListNamespaces(context.Context, *connect.Request[v1.ListNamespacesRequest]) (*connect.Response[v1.ListNamespacesResponse], error)
	ListServices(context.Context, *connect.Request[v1.ListServicesRequest]) (*connect.Response[v1.ListServicesResponse], error)
	GetService(context.Context, *connect.Request[v1.GetServiceRequest]) (*connect.Response[v1.GetServiceResponse], error)
	LaunchService(context.Context, *connect.Request[v1.LaunchServiceRequest]) (*connect.Response[v1.LaunchServiceResponse], error)
	DeleteService(context.Context, *connect.Request[v1.DeleteServiceRequest]) (*connect.Response[v1.DeleteServiceResponse], error)
	ScaleService(context.Context, *connect.Request[v1.ScaleServiceRequest]) (*connect.Response[v1.ScaleServiceResponse], error)
	SandboxExec(context.Context, *connect.Request[v1.SandboxExecRequest]) (*connect.Response[v1.SandboxExecResponse], error)
	SandboxRead(context.Context, *connect.Request[v1.SandboxReadRequest]) (*connect.Response[v1.SandboxReadResponse], error)
	SandboxWrite(context.Context, *connect.Request[v1.SandboxWriteRequest]) (*connect.Response[v1.SandboxWriteResponse], error)
	SandboxJobKill(context.Context, *connect.Request[v1.SandboxJobKillRequest]) (*connect.Response[v1.SandboxJobKillResponse], error)
	ListTasks(context.Context, *connect.Request[v1.ListTasksRequest]) (*connect.Response[v1.ListTasksResponse], error)
	GetTask(context.Context, *connect.Request[v1.GetTaskRequest]) (*connect.Response[v1.GetTaskResponse], error)
	Build(context.Context, *connect.Request[v1.BuildRequest]) (*connect.Response[v1.BuildResponse], error)
	Run(context.Context, *connect.Request[v1.RunRequest]) (*connect.Response[v1.RunResponse], error)
	TaskLog(context.Context, *connect.Request[v1.TaskLogRequest], *connect.ServerStream[v1.TaskLogResponse]) error
}

// NewOpsServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewOpsServiceHandler(svc OpsServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	opsServiceMethods := v1.File_easylab_v1_easylab_proto.Services().ByName("OpsService").Methods()
	opsServiceOpsStatusHandler := connect.NewUnaryHandler(
		OpsServiceOpsStatusProcedure,
		svc.OpsStatus,
		connect.WithSchema(opsServiceMethods.ByName("OpsStatus")),
		connect.WithHandlerOptions(opts...),
	)
	opsServiceListNamespacesHandler := connect.NewUnaryHandler(
		OpsServiceListNamespacesProcedure,
		svc.ListNamespaces,
		connect.WithSchema(opsServiceMethods.ByName("ListNamespaces")),
		connect.WithHandlerOptions(opts...),
	)
	opsServiceListServicesHandler := connect.NewUnaryHandler(
		OpsServiceListServicesProcedure,
		svc.ListServices,
		connect.WithSchema(opsServiceMethods.ByName("ListServices")),
		connect.WithHandlerOptions(opts...),
	)
	opsServiceGetServiceHandler := connect.NewUnaryHandler(
		OpsServiceGetServiceProcedure,
		svc.GetService,
		connect.WithSchema(opsServiceMethods.ByName("GetService")),
		connect.WithHandlerOptions(opts...),
	)
	opsServiceLaunchServiceHandler := connect.NewUnaryHandler(
		OpsServiceLaunchServiceProcedure,
		svc.LaunchService,
		connect.WithSchema(opsServiceMethods.ByName("LaunchService")),
		connect.WithHandlerOptions(opts...),
	)
	opsServiceDeleteServiceHandler := connect.NewUnaryHandler(
		OpsServiceDeleteServiceProcedure,
		svc.DeleteService,
		connect.WithSchema(opsServiceMethods.ByName("DeleteService")),
		connect.WithHandlerOptions(opts...),
	)
	opsServiceScaleServiceHandler := connect.NewUnaryHandler(
		OpsServiceScaleServiceProcedure,
		svc.ScaleService,
		connect.WithSchema(opsServiceMethods.ByName("ScaleService")),
		connect.WithHandlerOptions(opts...),
	)
	opsServiceSandboxExecHandler := connect.NewUnaryHandler(
		OpsServiceSandboxExecProcedure,
		svc.SandboxExec,
		connect.WithSchema(opsServiceMethods.ByName("SandboxExec")),
		connect.WithHandlerOptions(opts...),
	)
	opsServiceSandboxReadHandler := connect.NewUnaryHandler(
		OpsServiceSandboxReadProcedure,
		svc.SandboxRead,
		connect.WithSchema(opsServiceMethods.ByName("SandboxRead")),
		connect.WithHandlerOptions(opts...),
	)
	opsServiceSandboxWriteHandler := connect.NewUnaryHandler(
		OpsServiceSandboxWriteProcedure,
		svc.SandboxWrite,
		connect.WithSchema(opsServiceMethods.ByName("SandboxWrite")),
		connect.WithHandlerOptions(opts...),
	)
	opsServiceSandboxJobKillHandler := connect.NewUnaryHandler(
		OpsServiceSandboxJobKillProcedure,
		svc.SandboxJobKill,
		connect.WithSchema(opsServiceMethods.ByName("SandboxJobKill")),
		connect.WithHandlerOptions(opts...),
	)
	opsServiceListTasksHandler := connect.NewUnaryHandler(
		OpsServiceListTasksProcedure,
		svc.ListTasks,
		connect.WithSchema(opsServiceMethods.ByName("ListTasks")),
		connect.WithHandlerOptions(opts...),
	)
	opsServiceGetTaskHandler := connect.NewUnaryHandler(
		OpsServiceGetTaskProcedure,
		svc.GetTask,
		connect.WithSchema(opsServiceMethods.ByName("GetTask")),
		connect.WithHandlerOptions(opts...),
	)
	opsServiceBuildHandler := connect.NewUnaryHandler(
		OpsServiceBuildProcedure,
		svc.Build,
		connect.WithSchema(opsServiceMethods.ByName("Build")),
		connect.WithHandlerOptions(opts...),
	)
	opsServiceRunHandler := connect.NewUnaryHandler(
		OpsServiceRunProcedure,
		svc.Run,
		connect.WithSchema(opsServiceMethods.ByName("Run")),
		connect.WithHandlerOptions(opts...),
	)
	opsServiceTaskLogHandler := connect.NewServerStreamHandler(
		OpsServiceTaskLogProcedure,
		svc.TaskLog,
		connect.WithSchema(opsServiceMethods.ByName("TaskLog")),
		connect.WithHandlerOptions(opts...),
	)
	return "/easylab.v1.OpsService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case OpsServiceOpsStatusProcedure:
			opsServiceOpsStatusHandler.ServeHTTP(w, r)
		case OpsServiceListNamespacesProcedure:
			opsServiceListNamespacesHandler.ServeHTTP(w, r)
		case OpsServiceListServicesProcedure:
			opsServiceListServicesHandler.ServeHTTP(w, r)
		case OpsServiceGetServiceProcedure:
			opsServiceGetServiceHandler.ServeHTTP(w, r)
		case OpsServiceLaunchServiceProcedure:
			opsServiceLaunchServiceHandler.ServeHTTP(w, r)
		case OpsServiceDeleteServiceProcedure:
			opsServiceDeleteServiceHandler.ServeHTTP(w, r)
		case OpsServiceScaleServiceProcedure:
			opsServiceScaleServiceHandler.ServeHTTP(w, r)
		case OpsServiceSandboxExecProcedure:
			opsServiceSandboxExecHandler.ServeHTTP(w, r)
		case OpsServiceSandboxReadProcedure:
			opsServiceSandboxReadHandler.ServeHTTP(w, r)
		case OpsServiceSandboxWriteProcedure:
			opsServiceSandboxWriteHandler.ServeHTTP(w, r)
		case OpsServiceSandboxJobKillProcedure:
			opsServiceSandboxJobKillHandler.ServeHTTP(w, r)
		case OpsServiceListTasksProcedure:
			opsServiceListTasksHandler.ServeHTTP(w, r)
		case OpsServiceGetTaskProcedure:
			opsServiceGetTaskHandler.ServeHTTP(w, r)
		case OpsServiceBuildProcedure:
			opsServiceBuildHandler.ServeHTTP(w, r)
		case OpsServiceRunProcedure:
			opsServiceRunHandler.ServeHTTP(w, r)
		case OpsServiceTaskLogProcedure:
			opsServiceTaskLogHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedOpsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedOpsServiceHandler struct{}

func (UnimplementedOpsServiceHandler) OpsStatus(context.Context, *connect.Request[v1.OpsStatusRequest]) (*connect.Response[v1.OpsStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("easylab.v1.OpsService.OpsStatus is not implemented"))
}

func (UnimplementedOpsServiceHandler) ListNamespaces(context.Context, *connect.Request[v1.ListNamespacesRequest]) (*connect.Response[v1.ListNamespacesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("easylab.v1.OpsService.ListNamespaces is not implemented"))
}

func (UnimplementedOpsServiceHandler) ListServices(context.Context, *connect.Request[v1.ListServicesRequest]) (*connect.Response[v1.ListServicesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("easylab.v1.OpsService.ListServices is not implemented"))
}

func (UnimplementedOpsServiceHandler) GetService(context.Context, *connect.Request[v1.GetServiceRequest]) (*connect.Response[v1.GetServiceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("easylab.v1.OpsService.GetService is not implemented"))
}

func (UnimplementedOpsServiceHandler) LaunchService(context.Context, *connect.Request[v1.LaunchServiceRequest]) (*connect.Response[v1.LaunchServiceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("easylab.v1.OpsService.LaunchService is not implemented"))
}

func (UnimplementedOpsServiceHandler) DeleteService(context.Context, *connect.Request[v1.DeleteServiceRequest]) (*connect.Response[v1.DeleteServiceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("easylab.v1.OpsService.DeleteService is not implemented"))
}

func (UnimplementedOpsServiceHandler) ScaleService(context.Context, *connect.Request[v1.ScaleServiceRequest]) (*connect.Response[v1.ScaleServiceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("easylab.v1.OpsService.ScaleService is not implemented"))
}

func (UnimplementedOpsServiceHandler) SandboxExec(context.Context, *connect.Request[v1.SandboxExecRequest]) (*connect.Response[v1.SandboxExecResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("easylab.v1.OpsService.SandboxExec is not implemented"))
}

func (UnimplementedOpsServiceHandler) SandboxRead(context.Context, *connect.Request[v1.SandboxReadRequest]) (*connect.Response[v1.SandboxReadResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("easylab.v1.OpsService.SandboxRead is not implemented"))
}

func (UnimplementedOpsServiceHandler) SandboxWrite(context.Context, *connect.Request[v1.SandboxWriteRequest]) (*connect.Response[v1.SandboxWriteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("easylab.v1.OpsService.SandboxWrite is not implemented"))
}

func (UnimplementedOpsServiceHandler) SandboxJobKill(context.Context, *connect.Request[v1.SandboxJobKillRequest]) (*connect.Response[v1.SandboxJobKillResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("easylab.v1.OpsService.SandboxJobKill is not implemented"))
}

func (UnimplementedOpsServiceHandler) ListTasks(context.Context, *connect.Request[v1.ListTasksRequest]) (*connect.Response[v1.ListTasksResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("easylab.v1.OpsService.ListTasks is not implemented"))
}

func (UnimplementedOpsServiceHandler) GetTask(context.Context, *connect.Request[v1.GetTaskRequest]) (*connect.Response[v1.GetTaskResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("easylab.v1.OpsService.GetTask is not implemented"))
}

func (UnimplementedOpsServiceHandler) Build(context.Context, *connect.Request[v1.BuildRequest]) (*connect.Response[v1.BuildResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("easylab.v1.OpsService.Build is not implemented"))
}

func (UnimplementedOpsServiceHandler) Run(context.Context, *connect.Request[v1.RunRequest]) (*connect.Response[v1.RunResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("easylab.v1.OpsService.Run is not implemented"))
}

func (UnimplementedOpsServiceHandler) TaskLog(context.Context, *connect.Request[v1.TaskLogRequest], *connect.ServerStream[v1.TaskLogResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("easylab.v1.OpsService.TaskLog is not implemented"))
}

// RegistryServiceClient is a client for the easylab.v1.RegistryService service.
type RegistryServiceClient interface {
	ListPackageTypes(context.Context, *connect.Request[v1.ListPackageTypesRequest]) (*connect.Response[v1.ListPackageTypesResponse], error)
	ListPackages(context.Context, *connect.Request[v1.ListPackagesRequest]) (*connect.Response[v1.ListPackagesResponse], error)
	PackageVersions(context.Context, *connect.Request[v1.PackageVersionsRequest]) (*connect.Response[v1.PackageVersionsResponse], error)
	DeletePackage(context.Context, *connect.Request[v1.DeletePackageRequest]) (*connect.Response[v1.DeletePackageResponse], error)
	DeletePackageVersion(context.Context, *connect.Request[v1.DeletePackageVersionRequest]) (*connect.Response[v1.DeletePackageVersionResponse], error)
	ListPublishSpecs(context.Context, *connect.Request[v1.ListPublishSpecsRequest]) (*connect.Response[v1.ListPublishSpecsResponse], error)
}

// NewRegistryServiceClient constructs a client for the easylab.v1.RegistryService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewRegistryServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) RegistryServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	registryServiceMethods := v1.File_easylab_v1_easylab_proto.Services().ByName("RegistryService").Methods()
	return &registryServiceClient{
		listPackageTypes: connect.NewClient[v1.ListPackageTypesRequest, v1.ListPackageTypesResponse](
			httpClient,
			baseURL+RegistryServiceListPackageTypesProcedure,
			connect.WithSchema(registryServiceMethods.ByName("ListPackageTypes")),
			connect.WithClientOptions(opts...),
		),
		listPackages: connect.NewClient[v1.ListPackagesRequest, v1.ListPackagesResponse](
			httpClient,
			baseURL+RegistryServiceListPackagesProcedure,
			connect.WithSchema(registryServiceMethods.ByName("ListPackages")),
			connect.WithClientOptions(opts...),
		),
		packageVersions: connect.NewClient[v1.PackageVersionsRequest, v1.PackageVersionsResponse](
			httpClient,
			baseURL+RegistryServicePackageVersionsProcedure,
			connect.WithSchema(registryServiceMethods.ByName("PackageVersions")),
			connect.WithClientOptions(opts...),
		),
		deletePackage: connect.NewClient[v1.DeletePackageRequest, v1.DeletePackageResponse](
			httpClient,
			baseURL+RegistryServiceDeletePackageProcedure,
			connect.WithSchema(registryServiceMethods.ByName("DeletePackage")),
			connect.WithClientOptions(opts...),
		),
		deletePackageVersion: connect.NewClient[v1.DeletePackageVersionRequest, v1.DeletePackageVersionResponse](
			httpClient,
			baseURL+RegistryServiceDeletePackageVersionProcedure,
			connect.WithSchema(registryServiceMethods.ByName("DeletePackageVersion")),
			connect.WithClientOptions(opts...),
		),
		listPublishSpecs: connect.NewClient[v1.ListPublishSpecsRequest, v1.ListPublishSpecsResponse](
			httpClient,
			baseURL+RegistryServiceListPublishSpecsProcedure,
			connect.WithSchema(registryServiceMethods.ByName("ListPublishSpecs")),
			connect.WithClientOptions(opts...),
		),
	}
}

// registryServiceClient implements RegistryServiceClient.
type registryServiceClient struct {
	listPackageTypes     *connect.Client[v1.ListPackageTypesRequest, v1.ListPackageTypesResponse]
	listPackages         *connect.Client[v1.ListPackagesRequest, v1.ListPackagesResponse]
	packageVersions      *connect.Client[v1.PackageVersionsRequest, v1.PackageVersionsResponse]
	deletePackage        *connect.Client[v1.DeletePackageRequest, v1.DeletePackageResponse]
	deletePackageVersion *connect.Client[v1.DeletePackageVersionRequest, v1.DeletePackageVersionResponse]
	listPublishSpecs     *connect.Client[v1.ListPublishSpecsRequest, v1.ListPublishSpecsResponse]
}

// ListPackageTypes calls easylab.v1.RegistryService.ListPackageTypes.
func (c *registryServiceClient) ListPackageTypes(ctx context.Context, req *connect.Request[v1.ListPackageTypesRequest]) (*connect.Response[v1.ListPackageTypesResponse], error) {
	return c.listPackageTypes.CallUnary(ctx, req)
}

// ListPackages calls easylab.v1.RegistryService.ListPackages.
func (c *registryServiceClient) ListPackages(ctx context.Context, req *connect.Request[v1.ListPackagesRequest]) (*connect.Response[v1.ListPackagesResponse], error) {
	return c.listPackages.CallUnary(ctx, req)
}

// PackageVersions calls easylab.v1.RegistryService.PackageVersions.
func (c *registryServiceClient) PackageVersions(ctx context.Context, req *connect.Request[v1.PackageVersionsRequest]) (*connect.Response[v1.PackageVersionsResponse], error) {
	return c.packageVersions.CallUnary(ctx, req)
}

// DeletePackage calls easylab.v1.RegistryService.DeletePackage.
func (c *registryServiceClient) DeletePackage(ctx context.Context, req *connect.Request[v1.DeletePackageRequest]) (*connect.Response[v1.DeletePackageResponse], error) {
	return c.deletePackage.CallUnary(ctx, req)
}

// DeletePackageVersion calls easylab.v1.RegistryService.DeletePackageVersion.
func (c *registryServiceClient) DeletePackageVersion(ctx context.Context, req *connect.Request[v1.DeletePackageVersionRequest]) (*connect.Response[v1.DeletePackageVersionResponse], error) {
	return c.deletePackageVersion.CallUnary(ctx, req)
}

// ListPublishSpecs calls easylab.v1.RegistryService.ListPublishSpecs.
func (c *registryServiceClient) ListPublishSpecs(ctx context.Context, req *connect.Request[v1.ListPublishSpecsRequest]) (*connect.Response[v1.ListPublishSpecsResponse], error) {
	return c.listPublishSpecs.CallUnary(ctx, req)
}

// RegistryServiceHandler is an implementation of the easylab.v1.RegistryService service.
type RegistryServiceHandler interface {
	ListPackageTypes(context.Context, *connect.Request[v1.ListPackageTypesRequest]) (*connect.Response[v1.ListPackageTypesResponse], error)
	ListPackages(context.Context, *connect.Request[v1.ListPackagesRequest]) (*connect.Response[v1.ListPackagesResponse], error)
	PackageVersions(context.Context, *connect.Request[v1.PackageVersionsRequest]) (*connect.Response[v1.PackageVersionsResponse], error)
	DeletePackage(context.Context, *connect.Request[v1.DeletePackageRequest]) (*connect.Response[v1.DeletePackageResponse], error)
	DeletePackageVersion(context.Context, *connect.Request[v1.DeletePackageVersionRequest]) (*connect.Response[v1.DeletePackageVersionResponse], error)
	ListPublishSpecs(context.Context, *connect.Request[v1.ListPublishSpecsRequest]) (*connect.Response[v1.ListPublishSpecsResponse], error)
}

// NewRegistryServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewRegistryServiceHandler(svc RegistryServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	registryServiceMethods := v1.File_easylab_v1_easylab_proto.Services().ByName("RegistryService").Methods()
	registryServiceListPackageTypesHandler := connect.NewUnaryHandler(
		RegistryServiceListPackageTypesProcedure,
		svc.ListPackageTypes,
		connect.WithSchema(registryServiceMethods.ByName("ListPackageTypes")),
		connect.WithHandlerOptions(opts...),
	)
	registryServiceListPackagesHandler := connect.NewUnaryHandler(
		RegistryServiceListPackagesProcedure,
		svc.ListPackages,
		connect.WithSchema(registryServiceMethods.ByName("ListPackages")),
		connect.WithHandlerOptions(opts...),
	)
	registryServicePackageVersionsHandler := connect.NewUnaryHandler(
		RegistryServicePackageVersionsProcedure,
		svc.PackageVersions,
		connect.WithSchema(registryServiceMethods.ByName("PackageVersions")),
		connect.WithHandlerOptions(opts...),
	)
	registryServiceDeletePackageHandler := connect.NewUnaryHandler(
		RegistryServiceDeletePackageProcedure,
		svc.DeletePackage,
		connect.WithSchema(registryServiceMethods.ByName("DeletePackage")),
		connect.WithHandlerOptions(opts...),
	)
	registryServiceDeletePackageVersionHandler := connect.NewUnaryHandler(
		RegistryServiceDeletePackageVersionProcedure,
		svc.DeletePackageVersion,
		connect.WithSchema(registryServiceMethods.ByName("DeletePackageVersion")),
		connect.WithHandlerOptions(opts...),
	)
	registryServiceListPublishSpecsHandler := connect.NewUnaryHandler(
		RegistryServiceListPublishSpecsProcedure,
		svc.ListPublishSpecs,
		connect.WithSchema(registryServiceMethods.ByName("ListPublishSpecs")),
		connect.WithHandlerOptions(opts...),
	)
	return "/easylab.v1.RegistryService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case RegistryServiceListPackageTypesProcedure:
			registryServiceListPackageTypesHandler.ServeHTTP(w, r)
		case RegistryServiceListPackagesProcedure:
			registryServiceListPackagesHandler.ServeHTTP(w, r)
		case RegistryServicePackageVersionsProcedure:
			registryServicePackageVersionsHandler.ServeHTTP(w, r)
		case RegistryServiceDeletePackageProcedure:
			registryServiceDeletePackageHandler.ServeHTTP(w, r)
		case RegistryServiceDeletePackageVersionProcedure:
			registryServiceDeletePackageVersionHandler.ServeHTTP(w, r)
		case RegistryServiceListPublishSpecsProcedure:
			registryServiceListPublishSpecsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedRegistryServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedRegistryServiceHandler struct{}

func (UnimplementedRegistryServiceHandler) ListPackageTypes(context.Context, *connect.Request[v1.ListPackageTypesRequest]) (*connect.Response[v1.ListPackageTypesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("easylab.v1.RegistryService.ListPackageTypes is not implemented"))
}

func (UnimplementedRegistryServiceHandler) ListPackages(context.Context, *connect.Request[v1.ListPackagesRequest]) (*connect.Response[v1.ListPackagesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("easylab.v1.RegistryService.ListPackages is not implemented"))
}

func (UnimplementedRegistryServiceHandler) PackageVersions(context.Context, *connect.Request[v1.PackageVersionsRequest]) (*connect.Response[v1.PackageVersionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("easylab.v1.RegistryService.PackageVersions is not implemented"))
}

func (UnimplementedRegistryServiceHandler) DeletePackage(context.Context, *connect.Request[v1.DeletePackageRequest]) (*connect.Response[v1.DeletePackageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("easylab.v1.RegistryService.DeletePackage is not implemented"))
}

func (UnimplementedRegistryServiceHandler) DeletePackageVersion(context.Context, *connect.Request[v1.DeletePackageVersionRequest]) (*connect.Response[v1.DeletePackageVersionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("easylab.v1.RegistryService.DeletePackageVersion is not implemented"))
}

func (UnimplementedRegistryServiceHandler) ListPublishSpecs(context.Context, *connect.Request[v1.ListPublishSpecsRequest]) (*connect.Response[v1.ListPublishSpecsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("easylab.v1.RegistryService.ListPublishSpecs is not implemented"))
}
